// This file is part of midnightntwrk/example-bboard.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the Midnight bulletin board example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  ManoIssuerAPI,
  ManoParticipantAPI,
  EphemeralPrivateStateProvider,
  createIssuerPrivateState,
  deriveManoPublicState,
  issuerPrivateStateKey,
  participantPrivateStateKey,
  type IssuerProviders,
  type ParticipantProviders,
  type IssuerPrivateState,
  type ParticipantPrivateState,
} from '../../api/src/index';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { ledger, type Ledger, pureCircuits } from '../../contract/src/managed/bboard/contract/index.js';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress, toHex } from '@midnight-ntwrk/midnight-js-utils';
import { TestEnvironment } from '@midnight-ntwrk/testkit-js';
import { MidnightWalletProvider } from './midnight-wallet-provider';
import { randomBytes } from '../../api/src/utils';
import { unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { syncWallet, waitForUnshieldedFunds } from './wallet-utils';
import { generateDust } from './generate-dust';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getBBoardLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific bulletin board contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the bulletin board contract.
 */

export const getManoLedgerState = async (
  publicDataProvider: IssuerProviders['publicDataProvider'] | ParticipantProviders['publicDataProvider'],
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};

const displayLedgerState = async (
  publicDataProvider: IssuerProviders['publicDataProvider'] | ParticipantProviders['publicDataProvider'],
  contractAddress: ContractAddress,
  logger: Logger,
): Promise<void> => {
  const ledgerState = await getManoLedgerState(publicDataProvider, contractAddress);
  if (ledgerState === null) {
    logger.info(`No MANO contract deployed at ${contractAddress}`);
    return;
  }
  const s = deriveManoPublicState(ledgerState);
  logger.info(`Enrolled credentials: ${s.enrollmentCount}`);
  logger.info(`Total check-ins: ${s.totalCheckIns}`);
  logger.info(`Nullifiers used: ${s.nullifierCount}`);
  logger.info(`Issuer public key: ${toHex(s.issuerPk)}`);
  logger.info(`Credential tree full: ${s.treeIsFull}`);
};

/* **********************************************************************
 * Issuer mode. Deploys the contract and enrolls participant credentials.
 * The participant secret key is generated here, shown once so it can be
 * written to a card, and then discarded. It is never stored.
 */

const ISSUER_MENU = `
Issuer mode:
  1. Deploy a new MANO credential contract
  2. Join an existing MANO contract
  3. Exit
Which would you like to do? `;

const ISSUER_LOOP = `
Issuer mode:
  1. Enroll a new participant credential
  2. Display the current ledger state
  3. Exit
Which would you like to do? `;

const issuerLoop = async (providers: IssuerProviders, issuerSecretKey: Uint8Array, rli: Interface, logger: Logger): Promise<void> => {
  let api: ManoIssuerAPI | null = null;
  while (api === null) {
    const choice = await rli.question(ISSUER_MENU);
    switch (choice) {
      case '1':
        api = await ManoIssuerAPI.deploy(providers, issuerSecretKey, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        break;
      case '2':
        api = await ManoIssuerAPI.join(providers, await rli.question('Contract address (hex)? '), issuerSecretKey, logger);
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        break;
      case '3':
        return;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
  const issuer: ManoIssuerAPI = api;
  while (true) {
    const choice = await rli.question(ISSUER_LOOP);
    try {
      switch (choice) {
        case '1': {
          const sk = randomBytes(32);
          const commitment = pureCircuits.publicCommitment(sk);
          await issuer.enroll(commitment);
          logger.info('Credential enrolled.');
          logger.info(`CARD SECRET (write to card, not stored anywhere): ${toHex(sk)}`);
          break;
        }
        case '2':
          await displayLedgerState(providers.publicDataProvider, issuer.deployedContractAddress, logger);
          break;
        case '3':
          logger.info('Exiting...');
          return;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    } catch (e) {
      logError(logger, e);
      logger.info('Returning to menu...');
    }
  }
};

/* **********************************************************************
 * Participant mode. Joins an existing contract with a secret key read
 * from a card. The key is held in memory only and cleared after each
 * proof.
 */

const PARTICIPANT_LOOP = `
Participant mode:
  1. Check in for today
  2. Verify credential
  3. Display the current ledger state
  4. Exit
Which would you like to do? `;

const participantLoop = async (providers: ParticipantProviders, rli: Interface, logger: Logger): Promise<void> => {
  const address = await rli.question('Contract address (hex)? ');
  const cardSecret = await rli.question('Card secret (hex)? ');
  const sk = Uint8Array.from(Buffer.from(cardSecret.replace(/^0x/, ''), 'hex'));
  if (sk.length !== 32) {
    logger.error('Card secret must be 32 bytes of hex.');
    return;
  }
  const api = await ManoParticipantAPI.join(providers, address, sk, logger);
  logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
  while (true) {
    const choice = await rli.question(PARTICIPANT_LOOP);
    try {
      switch (choice) {
        case '1': {
          const today = new TextEncoder().encode(new Date().toISOString().slice(0, 10).padEnd(32, '\0'));
          await api.checkIn(today.slice(0, 32));
          logger.info('Checked in.');
          break;
        }
        case '2':
          await api.verifyCredential();
          logger.info('Credential verified.');
          break;
        case '3':
          await displayLedgerState(providers.publicDataProvider, api.deployedContractAddress, logger);
          break;
        case '4':
          logger.info('Exiting...');
          await api.close();
          return;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    } catch (e) {
      logError(logger, e);
      logger.info('Returning to menu...');
    }
  }
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<string | undefined> => {
  if (config instanceof StandaloneConfig) {
    return GENESIS_MINT_WALLET_SEED;
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return toHex(randomBytes(32));
      case '2':
        return await rli.question('Enter your wallet seed: ');
      case '3':
        logger.info('Exiting...');
        return undefined;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * run: the main entry point that starts the whole bulletin board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, testEnv: TestEnvironment, logger: Logger): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  const providersToBeStopped: MidnightWalletProvider[] = [];
  try {
    const envConfiguration = await testEnv.start();
    logger.info(`Environment started with configuration: ${JSON.stringify(envConfiguration)}`);
    const seed = await buildWallet(config, rli, logger);
    if (seed === undefined) {
      return;
    }
    const walletProvider = await MidnightWalletProvider.build(logger, envConfiguration, seed);
    providersToBeStopped.push(walletProvider);
    const walletFacade: WalletFacade = walletProvider.wallet;

    await walletProvider.start();

    const unshieldedState = await waitForUnshieldedFunds(logger, walletFacade, envConfiguration, unshieldedToken());
    const nightBalance = unshieldedState.balances[unshieldedToken().raw];
    if (nightBalance === undefined) {
      logger.info('No funds received, exiting...');
      return;
    }
    logger.info(`Your NIGHT wallet balance is: ${nightBalance}`);

    if (config.generateDust) {
      const dustGeneration = await generateDust(logger, seed, unshieldedState, walletFacade);
      if (dustGeneration) {
        logger.info(`Submitted dust generation registration transaction: ${dustGeneration}`);
        await syncWallet(logger, walletFacade);
      }
    }

    while (true) {
      const ROLE_QUESTION = `
  Select a role:
    1. Issuer (issuing organization - deploy and enroll credentials)
    2. Participant (check in with a card)
    3. Exit
  Which are you? `;

      const role = await rli.question(ROLE_QUESTION);
      if (role === '3') {
        logger.info('Exiting...');
        break;
      }
      if (role !== '1' && role !== '2') {
        logger.error(`Invalid choice: ${role}`);
        continue;
      }

      const publicDataProvider = indexerPublicDataProvider(envConfiguration.indexer, envConfiguration.indexerWS);

      if (role === '1') {
        const zkConfigProvider = new NodeZkConfigProvider<'enroll'>(config.zkConfigPath);
        const issuerSeed = await rli.question('Issuer secret key (hex, blank to generate a new one): ');
        const issuerSecretKey =
          issuerSeed.trim() === ''
            ? randomBytes(32)
            : Uint8Array.from(Buffer.from(issuerSeed.trim().replace(/^0x/, ''), 'hex'));
        if (issuerSecretKey.length !== 32) {
          logger.error('Issuer secret key must be 32 bytes of hex.');
          continue;
        }
        if (issuerSeed.trim() === '') {
          logger.info(`Generated issuer secret key (SAVE THIS - required to enroll again): ${toHex(issuerSecretKey)}`);
        }
        const providers: IssuerProviders = {
          privateStateProvider: levelPrivateStateProvider<typeof issuerPrivateStateKey, IssuerPrivateState>({
            privateStateStoreName: `${config.privateStateStoreName}-issuer`,
            signingKeyStoreName: `${config.privateStateStoreName}-issuer-signing-keys`,
            privateStoragePasswordProvider: () => {
              return 'Mano-Issuer-2026!';
            },
            accountId: seed,
          }),
          publicDataProvider,
          zkConfigProvider,
          proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
          walletProvider,
          midnightProvider: walletProvider,
        };
        await issuerLoop(providers, issuerSecretKey, rli, logger);
      } else {
        const zkConfigProvider = new NodeZkConfigProvider<'checkIn' | 'verifyCredential'>(config.zkConfigPath);
        const providers: ParticipantProviders = {
          privateStateProvider: new EphemeralPrivateStateProvider<typeof participantPrivateStateKey, ParticipantPrivateState>(),
          publicDataProvider,
          zkConfigProvider,
          proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
          walletProvider,
          midnightProvider: walletProvider,
        };
        await participantLoop(providers, rli, logger);
      }
    }
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        for (const wallet of providersToBeStopped) {
          logger.info('Stopping wallet...');
          await wallet.stop();
        }
        if (testEnv) {
          logger.info('Stopping test environment...');
          await testEnv.shutdown();
        }
      } catch (e) {
        logError(logger, e);
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
